spring:
  application:
    name: config-server-app
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/yevhen.hryshchenko/Documents/Projects/configServerApp/config-repo
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'
