spring:
  application:
    name: zuul-api-gateway
server:
  port: 8881
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

#zuul:
#  routes:
#    api-v1:
#         url: http://localhost:8080
